version: '3.8'

services:
  pocketbase:
    image: adrianmusante/pocketbase:0.34
    container_name: pifatro_pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase_data:/pb_data
      - ./public/pocketbase:/backup:ro

  web:
    image: nginx:1.29.3-alpine
    container_name: pifatro_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pocketbase
